export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SHOPPING_CART_INIT = 'SHOPPING_CART_INIT';
export const SET_SHOPPING_CART = 'SET_SHOPPING_CART';
export const ADD_SHOPPING_CART_ITEM = 'ADD_SHOPPING_CART_ITEM';
export const REMOVE_SHOPPING_CART_ITEM = 'REMOVE_SHOPPING_CART_ITEM';
